-- =========================
--  CLINIC API - SCHEMA H2
-- =========================

DROP TABLE IF EXISTS user_roles;
DROP TABLE IF EXISTS app_users;
DROP TABLE IF EXISTS roles;

DROP TABLE IF EXISTS invoice_lines;
DROP TABLE IF EXISTS invoices;

DROP TABLE IF EXISTS appointments;

DROP TABLE IF EXISTS doctor_specialties;

DROP TABLE IF EXISTS medical_services;
DROP TABLE IF EXISTS doctors;
DROP TABLE IF EXISTS patients;

-- -------------------------
-- PATIENTS
-- -------------------------
CREATE TABLE patients (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          dni VARCHAR(20) NOT NULL,
                          full_name VARCHAR(120) NOT NULL,
                          email VARCHAR(150) NOT NULL,
                          phone VARCHAR(30),
                          date_of_birth DATE,
                          active BOOLEAN NOT NULL
);

CREATE UNIQUE INDEX uk_patient_dni ON patients(dni);

-- -------------------------
-- DOCTORS
-- -------------------------
CREATE TABLE doctors (
                         id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         license_number VARCHAR(40) NOT NULL,
                         full_name VARCHAR(120) NOT NULL,
                         email VARCHAR(150) NOT NULL,
                         active BOOLEAN NOT NULL
);

CREATE UNIQUE INDEX uk_doctor_license ON doctors(license_number);

-- -------------------------
-- MEDICAL SERVICES
-- -------------------------
CREATE TABLE medical_services (
                                  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                  code VARCHAR(30) NOT NULL,
                                  name VARCHAR(120) NOT NULL,
                                  base_price DECIMAL(12,2) NOT NULL,
                                  active BOOLEAN NOT NULL
);

CREATE UNIQUE INDEX uk_medical_service_code ON medical_services(code);

-- -------------------------
-- VERSIÓN ONE2MANY....
-- DOCTOR_SPECIALTIES (entity intermedia con PK compuesta)
-- PK: (doctor_id, specialty)
-- -------------------------
-- CREATE TABLE doctor_specialties (
--                                     doctor_id BIGINT NOT NULL,
--                                     specialty VARCHAR(30) NOT NULL,
--                                     level VARCHAR(20) NOT NULL,
--                                     active BOOLEAN NOT NULL,
--                                     since_date DATE NOT NULL,
--                                     consultation_fee_override DECIMAL(12,2),
--
--                                     CONSTRAINT pk_doctor_specialties PRIMARY KEY (doctor_id, specialty),
--                                     CONSTRAINT fk_doctor_specialties_doctor
--                                         FOREIGN KEY (doctor_id) REFERENCES doctors(id)
-- );

-- -------------------------

CREATE TABLE specialties (
                             id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             code VARCHAR(30) NOT NULL,
                             name VARCHAR(80) NOT NULL,
                             active BOOLEAN NOT NULL
);

CREATE UNIQUE INDEX uk_specialty_code ON specialties(code);

-- -------------------------
-- DOCTOR_SPECIALTIES (tabla intermedia N:M con atributos)
-- Un doctor puede tener varias especialidades
-- Una especialidad puede estar asociada a varios doctores
-- Un doctor NO puede repetir la misma especialidad (PK compuesta)
-- -------------------------
CREATE TABLE doctor_specialties (
                                    doctor_id BIGINT NOT NULL,
                                    specialty_id BIGINT NOT NULL,
                                    level VARCHAR(20) NOT NULL,
                                    active BOOLEAN NOT NULL,
                                    since_date DATE NOT NULL,
                                    consultation_fee_override DECIMAL(12,2),

                                    CONSTRAINT pk_doctor_specialties PRIMARY KEY (doctor_id, specialty_id),
                                    CONSTRAINT fk_ds_doctor FOREIGN KEY (doctor_id) REFERENCES doctors(id),
                                    CONSTRAINT fk_ds_specialty FOREIGN KEY (specialty_id) REFERENCES specialties(id)
);
-- -------------------------
-- APPOINTMENTS
-- -------------------------
CREATE TABLE appointments (
                              id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                              patient_id BIGINT NOT NULL,
                              doctor_id BIGINT NOT NULL,
                              start_at TIMESTAMP NOT NULL,
                              end_at TIMESTAMP NOT NULL,
                              minutes INT NOT NULL,
                              status VARCHAR(20) NOT NULL,
                              reason VARCHAR(250),
                              cancellation_reason VARCHAR(250),

                              CONSTRAINT fk_appointments_patient
                                  FOREIGN KEY (patient_id) REFERENCES patients(id),
                              CONSTRAINT fk_appointments_doctor
                                  FOREIGN KEY (doctor_id) REFERENCES doctors(id)
);

CREATE INDEX idx_appointment_doctor_start ON appointments(doctor_id, start_at);
CREATE INDEX idx_appointment_patient_start ON appointments(patient_id, start_at);

-- -------------------------
-- INVOICES (1-1 con appointment)
-- -------------------------
CREATE TABLE invoices (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          appointment_id BIGINT NOT NULL,
                          status VARCHAR(20) NOT NULL,
                          subtotal DECIMAL(12,2) NOT NULL,
                          tax_total DECIMAL(12,2) NOT NULL,
                          total DECIMAL(12,2) NOT NULL,
                          issued_at TIMESTAMP,
                          paid_at TIMESTAMP,
                          payment_method VARCHAR(20),

                          CONSTRAINT uk_invoices_appointment UNIQUE (appointment_id),
                          CONSTRAINT fk_invoices_appointment
                              FOREIGN KEY (appointment_id) REFERENCES appointments(id)
);

-- -------------------------
-- INVOICE_LINES
-- -------------------------
CREATE TABLE invoice_lines (
                               id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                               invoice_id BIGINT NOT NULL,
                               service_id BIGINT NOT NULL,
                               quantity INT NOT NULL,
                               unit_price DECIMAL(12,2) NOT NULL,
                               vat_rate VARCHAR(10) NOT NULL,
                               discount_type VARCHAR(10) NOT NULL,
                               discount_value DECIMAL(12,2),
                               line_total DECIMAL(12,2) NOT NULL,

                               CONSTRAINT fk_invoice_lines_invoice
                                   FOREIGN KEY (invoice_id) REFERENCES invoices(id),
                               CONSTRAINT fk_invoice_lines_service
                                   FOREIGN KEY (service_id) REFERENCES medical_services(id)
);

CREATE INDEX idx_invoice_lines_invoice ON invoice_lines(invoice_id);

-- -------------------------
-- SECURITY TABLES
-- -------------------------
CREATE TABLE roles (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       name VARCHAR(40) NOT NULL
);

CREATE UNIQUE INDEX uk_roles_name ON roles(name);

CREATE TABLE app_users (
                           id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           username VARCHAR(60) NOT NULL,
                           password VARCHAR(100) NOT NULL,
                           enabled BOOLEAN NOT NULL
);

CREATE UNIQUE INDEX uk_users_username ON app_users(username);

CREATE TABLE user_roles (
                            user_id BIGINT NOT NULL,
                            role_id BIGINT NOT NULL,

                            CONSTRAINT pk_user_roles PRIMARY KEY (user_id, role_id),
                            CONSTRAINT fk_user_roles_user FOREIGN KEY (user_id) REFERENCES app_users(id),
                            CONSTRAINT fk_user_roles_role FOREIGN KEY (role_id) REFERENCES roles(id)
);
